CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE IF NOT EXISTS data_protection_keys (id integer GENERATED BY DEFAULT AS IDENTITY, friendly_name text, xml text, CONSTRAINT "PK_data_protection_keys" PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS o_auth_clients (client_id character varying(100) NOT NULL, primary_client_secret_hash text NOT NULL, secondary_client_secret_hash text, display_name character varying(200) NOT NULL, redirect_uris text[] NOT NULL, allowed_scopes text[] NOT NULL, is_trusted_for_exchange boolean NOT NULL, is_active boolean NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone, CONSTRAINT "PK_o_auth_clients" PRIMARY KEY (client_id));

CREATE TABLE IF NOT EXISTS users (id uuid NOT NULL DEFAULT (gen_random_uuid()), email character varying(255) NOT NULL, first_name character varying(100) NOT NULL, last_name character varying(100) NOT NULL, national_id character varying(11), phone_number character varying(20), email_verification_token text, email_verification_token_expires_at timestamp with time zone, email_verified boolean NOT NULL, password_reset_token text, password_reset_token_expires_at timestamp with time zone, is_active boolean NOT NULL DEFAULT TRUE, created_at timestamp with time zone NOT NULL DEFAULT (now()), CONSTRAINT "PK_users" PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS audit_logs (id uuid NOT NULL DEFAULT (gen_random_uuid()), user_id uuid, event_type character varying(50) NOT NULL, description character varying(1000) NOT NULL, ip_address character varying(45), user_agent character varying(500), timestamp timestamp with time zone NOT NULL DEFAULT (now()), metadata jsonb, CONSTRAINT "PK_audit_logs" PRIMARY KEY (id), CONSTRAINT "FK_audit_logs_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS auth_sessions (id uuid NOT NULL DEFAULT (gen_random_uuid()), user_id uuid NOT NULL, session_id character varying(128) NOT NULL, ip_address character varying(45) NOT NULL, user_agent character varying(500), created_at timestamp with time zone NOT NULL DEFAULT (now()), expires_at timestamp with time zone NOT NULL, is_active boolean NOT NULL DEFAULT TRUE, CONSTRAINT "PK_auth_sessions" PRIMARY KEY (id), CONSTRAINT "FK_auth_sessions_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS refresh_tokens (id uuid NOT NULL DEFAULT (gen_random_uuid()), user_id uuid NOT NULL, token_hash character varying(64) NOT NULL, expires_at timestamp with time zone NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT (now()), revoked_at timestamp with time zone, replaced_by_token_id text, CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (id), CONSTRAINT "FK_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS user_credentials (id uuid NOT NULL, password_hash character varying(255) NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT (now()), updated_at timestamp with time zone, must_change_password boolean NOT NULL, failed_login_attempts integer NOT NULL DEFAULT 0, last_failed_login_at timestamp with time zone, locked_until timestamp with time zone, CONSTRAINT "PK_user_credentials" PRIMARY KEY (id), CONSTRAINT "FK_user_credentials_users_id" FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS "IX_audit_logs_event_type" ON audit_logs (event_type);

CREATE INDEX IF NOT EXISTS "IX_audit_logs_timestamp" ON audit_logs (timestamp);

CREATE INDEX IF NOT EXISTS "IX_audit_logs_user_id" ON audit_logs (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_auth_sessions_session_id" ON auth_sessions (session_id);

CREATE INDEX IF NOT EXISTS "IX_auth_sessions_user_id_is_active" ON auth_sessions (user_id, is_active);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_refresh_tokens_token_hash" ON refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS "IX_refresh_tokens_user_id_revoked_at" ON refresh_tokens (user_id, revoked_at) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS "IX_user_credentials_id" ON user_credentials (id);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_email" ON users (email);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116210615_InitialCreate', '10.0.2');

COMMIT;

SELECT * FROM audit_logs ORDER BY timestamp DESC LIMIT 5;
