apiVersion: v1
kind: Secret
metadata:
  name: networcoid-secrets
  namespace: networcoid
type: Opaque
data:
  # Base64 encoded values
  database-url: SG9zdD1kYi5leGFtcGxlLmNvbTtEYXRhYmFzZT1uZXR3b3Jjb19hdXRoO1VzZXJuYW1lPXVzZXI7UGFzc3dvcmQ9cGFzcw==
  jwt-secret: Y2hhbmdlLW1lLXN1cGVyLXNlY3JldC1rZXktYXQtbGVhc3QtMzItY2hhcnM=
