apiVersion: v1
kind: Secret
metadata:
  name: networcoid-secrets
  namespace: networco-id
type: Opaque
data:
  # Values must be base64 encoded. 
  # Use: echo -n "value" | base64
  db-host: "cG9zdGdyZXM=" # "postgres"
  database-url: "" # Set via kubectl or local untracked file
  jwt-secret: ""   # Set via kubectl or local untracked file
  brevo-api-key: "" # Set via kubectl or local untracked file
  NATS_URL: "bmF0czovL25hdHMubmV0d29yY28taWQuc3ZjLmNsdXN0ZXIubG9jYWw6NDIyMg==" # This is internal DNS, safe to keep
