using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworcoId.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Fully idempotent migration - handles cases where tables may be auto-created
            // by Data Protection library or other initialization logic
            migrationBuilder.Sql(@"
                -- Ensure auth schema exists
                DO $SCHEMA$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
                        CREATE SCHEMA auth;
                    END IF;
                END $SCHEMA$;

                -- Create __EFMigrationsHistory table if it doesn't exist
                CREATE TABLE IF NOT EXISTS auth.""__EFMigrationsHistory"" (
                    ""MigrationId"" character varying(150) NOT NULL,
                    ""ProductVersion"" character varying(32) NOT NULL,
                    CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY (""MigrationId"")
                );

                -- Create data_protection_keys table
                DO $DPK$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'data_protection_keys'
                    ) THEN
                        CREATE TABLE auth.data_protection_keys (
                            id integer GENERATED BY DEFAULT AS IDENTITY,
                            friendly_name text,
                            xml text,
                            CONSTRAINT ""PK_data_protection_keys"" PRIMARY KEY (id)
                        );
                    END IF;
                END $DPK$;

                -- Create o_auth_clients table
                DO $OAC$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'o_auth_clients'
                    ) THEN
                        CREATE TABLE auth.o_auth_clients (
                            client_id character varying(100) NOT NULL,
                            primary_client_secret_hash text NOT NULL,
                            secondary_client_secret_hash text,
                            display_name character varying(200) NOT NULL,
                            redirect_uris text[] NOT NULL,
                            allowed_scopes text[] NOT NULL,
                            is_active boolean NOT NULL,
                            created_at timestamp with time zone NOT NULL,
                            updated_at timestamp with time zone,
                            CONSTRAINT ""PK_o_auth_clients"" PRIMARY KEY (client_id)
                        );
                    END IF;
                END $OAC$;

                -- Create users table
                DO $USR$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'users'
                    ) THEN
                        CREATE TABLE auth.users (
                            id uuid NOT NULL DEFAULT gen_random_uuid(),
                            email character varying(255) NOT NULL,
                            first_name character varying(100) NOT NULL,
                            last_name character varying(100) NOT NULL,
                            national_id character varying(11),
                            phone_number character varying(20),
                            email_verification_token text,
                            email_verification_token_expires_at timestamp with time zone,
                            email_verified boolean NOT NULL,
                            is_active boolean NOT NULL DEFAULT true,
                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                            CONSTRAINT ""PK_users"" PRIMARY KEY (id)
                        );
                    END IF;
                END $USR$;

                -- Create auth_sessions table
                DO $SESS$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'auth_sessions'
                    ) THEN
                        CREATE TABLE auth.auth_sessions (
                            id uuid NOT NULL DEFAULT gen_random_uuid(),
                            user_id uuid NOT NULL,
                            session_id character varying(128) NOT NULL,
                            ip_address character varying(45) NOT NULL,
                            user_agent character varying(500),
                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                            expires_at timestamp with time zone NOT NULL,
                            is_active boolean NOT NULL DEFAULT true,
                            CONSTRAINT ""PK_auth_sessions"" PRIMARY KEY (id),
                            CONSTRAINT ""FK_auth_sessions_users_user_id"" FOREIGN KEY (user_id)
                                REFERENCES auth.users (id) ON DELETE CASCADE
                        );
                    END IF;
                END $SESS$;

                -- Create refresh_tokens table
                DO $REFTOK$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'refresh_tokens'
                    ) THEN
                        CREATE TABLE auth.refresh_tokens (
                            id uuid NOT NULL DEFAULT gen_random_uuid(),
                            user_id uuid NOT NULL,
                            token_hash character varying(64) NOT NULL,
                            expires_at timestamp with time zone NOT NULL,
                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                            revoked_at timestamp with time zone,
                            replaced_by_token_id text,
                            CONSTRAINT ""PK_refresh_tokens"" PRIMARY KEY (id),
                            CONSTRAINT ""FK_refresh_tokens_users_user_id"" FOREIGN KEY (user_id)
                                REFERENCES auth.users (id) ON DELETE CASCADE
                        );
                    END IF;
                END $REFTOK$;

                -- Create user_credentials table
                DO $CRED$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_tables 
                        WHERE schemaname = 'auth' AND tablename = 'user_credentials'
                    ) THEN
                        CREATE TABLE auth.user_credentials (
                            id uuid NOT NULL,
                            password_hash character varying(255) NOT NULL,
                            created_at timestamp with time zone NOT NULL DEFAULT now(),
                            updated_at timestamp with time zone,
                            failed_login_attempts integer NOT NULL DEFAULT 0,
                            last_failed_login_at timestamp with time zone,
                            locked_until timestamp with time zone,
                            CONSTRAINT ""PK_user_credentials"" PRIMARY KEY (id),
                            CONSTRAINT ""FK_user_credentials_users_id"" FOREIGN KEY (id)
                                REFERENCES auth.users (id) ON DELETE CASCADE
                        );
                    END IF;
                END $CRED$;

                -- Create indexes if they don't exist
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_auth_sessions_session_id"" 
                    ON auth.auth_sessions (session_id);
                
                CREATE INDEX IF NOT EXISTS ""IX_auth_sessions_user_id_is_active"" 
                    ON auth.auth_sessions (user_id, is_active);
                
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_refresh_tokens_token_hash"" 
                    ON auth.refresh_tokens (token_hash);
                
                CREATE INDEX IF NOT EXISTS ""IX_refresh_tokens_user_id_revoked_at"" 
                    ON auth.refresh_tokens (user_id, revoked_at) 
                    WHERE revoked_at IS NULL;
                
                CREATE INDEX IF NOT EXISTS ""IX_user_credentials_id"" 
                    ON auth.user_credentials (id);
                
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_users_email"" 
                    ON auth.users (email);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "auth_sessions",
                schema: "auth");

            migrationBuilder.DropTable(
                name: "data_protection_keys",
                schema: "auth");

            migrationBuilder.DropTable(
                name: "o_auth_clients",
                schema: "auth");

            migrationBuilder.DropTable(
                name: "refresh_tokens",
                schema: "auth");

            migrationBuilder.DropTable(
                name: "user_credentials",
                schema: "auth");

            migrationBuilder.DropTable(
                name: "users",
                schema: "auth");
        }
    }
}
